version: 2.1
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
workflows:
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
notify:
   webhooks:
     -url: https://hooks.glipdemo.com/webhook/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvdCI6InUiLCJvaSI6IjE1NDk5NzQ3MzMxIiwiaWQiOiIyNDY1NDY0NTkifQ.rLvWAfXlhxIn27QSRzqbrkX1Cs6sVJzK-SxS4XWOzlQ
